### ISSUE TITLE
使用kubeapps-plus部署应用，gitlab显示未就绪，jenkins显示就绪，但是访问都提示Service Unavailable

### ISSUE THREAD

**Issue by leksas** [KubeOperator/kubeapps-plus#13]
** kubeapps-plus 版本**
您所使用的 kubeapps-plus 版本是？
kubeOperator-v2.4.43-release

**Bug 描述**
简要描述您碰到的问题
使用kubeapps-plus部署应用后，应用无法访问

![image](https://user-images.githubusercontent.com/62830140/78516179-4660f280-77eb-11ea-8452-ad670ff1e84b.png)

![image](https://user-images.githubusercontent.com/62830140/78516202-55e03b80-77eb-11ea-957a-bf91e622461a.png)

**Bug 重现步骤**
1. 使用kukubeapps-plus部署应用
2. 修改hosts文件，绑定应用
3.访问应用

**Comment by lvxiaohu** [comment]
1 .通过 Kubeapps-plus 应用商店部署完 jenkins 后，可稍微等待 2～3 分钟，服务可能还启动中，但这不代表错误。

2.若长时间无法正常访问，请登录到 Master 节点，执行以下命令并向我反馈日志信息。
$ kubectl describe pod  jenkins-nchfuq -n kube-system
$ kubectl logs -f jenkins-nchfuq -n kube-system

**Comment by krisbai** [comment]
同样的报错，describe看了下是镜像拉取不下来。

**Comment by lvxiaohu** [comment]
那需要检查下镜像 pull 不下来的原因。

**Comment by krisbai** [comment]
> 那需要检查下镜像 pull 不下来的原因。

registry.kubeapps.fit2cloud.com/kubeapps-plus 镜像仓库搜不到了

**Comment by lvxiaohu** [comment]
可以截图看一下吗？ 这个不是你部署 Jenkins 所需要的镜像。

**Comment by krisbai** [comment]
> 可以截图看一下吗？ 这个不是你部署 Jenkins 所需要的镜像。

![kube](https://user-images.githubusercontent.com/10414888/81669437-cf1d1f00-9478-11ea-8757-9c1813625d1d.jpg)

**Comment by lvxiaohu** [comment]
请确认镜像仓库中有 busybox:1.25.0 这个镜像吗？ 你可以手动执行 docker pull 进行测试。

**Comment by lvxiaohu** [comment]
由于此问题长时间未活动，我先关闭这个问题。如果问题还存在，请重新提交。
