### ISSUE TITLE
helm2安装报错

### ISSUE THREAD

**Issue by rhkjyn** [KubeOperator/kubeapps-plus#8]
执行安装时报错，如下信息，请问如何解决

Error: getting deployed release "kubeapps-plus": release: "kubeapps-plus" not found

docker  Version:           18.09.9
k8s version:      v1.14.8

**Comment by lvxiaohu** [comment]
1.请描述一下你的 KubeOperator 版本 。
2.可尝试登录到 Master 执行：
$ cd /opt/kubeOperator-kube-bin/1.1x.xx/manifests/   # 替换为你的对应版本
$ helm upgrade kubeapps-plus --namespace=kubeapps-plus --install --force --recreate-pods ./kubeapps-plus

如问题依旧存在，也可在社区交流群里沟通，这样更方便排查问题。

**Comment by lvxiaohu** [comment]
由于问题长时间未得到回复，暂且关闭。如果你的问题依旧存在或者还有其他的问题，可以重新提交 Issue。
